app:
  name: app-go
  env: dev
  api_url: localhost:8080
  allowed_origins:
    - http://localhost:8080
    - http://127.0.0.1:8080
  audience: chatX Audience
  issuer: chatX Issuer

server:
  port: "8080"

database:
  addr: "5432"
  host: localhost
  user: admin
  password: admin
  name: chat_db
  max_open_conns: 9
  max_idle_conns: 6
  max_idle_time: 15m

email:
  host: "sandbox.smtp.mailtrap.io"
  port: 2525
  username: "4ffa30e68273f7"
  password: "268f9adca7e33e"
  fromEmail: "jayhun231@gmail.com"

auth:
  secret_key: "your-secret-key"

